
name: organic_bloom_erp
description: Vyapar style ERP for Organic Bloom Cosmetics

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.3.0
  path: ^1.8.3

flutter:
  uses-material-design: true
